/** @file "/owlcpp/include/owlcpp/terms/iri_tags_system.hpp" 
part of owlcpp project.
@n @n Distributed under the Boost Software License, Version 1.0; see doc/license.txt.
@n Copyright Mikhail K Levin 2012
*******************************************************************************/
#ifndef IRI_TAGS_SYSTEM_HPP_
#define IRI_TAGS_SYSTEM_HPP_

/**@brief Define set of common system namespaces.
@details This macro is used for generating types and typelists.
((class name)("standard prefix")("IRI"))
*******************************************************************************/
#define OWLCPP_IRI_LIST_SYSTEM \
   ((empty)("")("")) \
   ((blank)("_")("_")) \
/* */

#include "owlcpp/terms/uri_macro.hpp"
#include "owlcpp/ns_id.hpp"

namespace owlcpp{ namespace terms{

/**@struct N_xxx
@brief Namespace IRI tag classes generated by macro OWLCPP_GENERATE_IRI_TAGS
@details Declare types for each system IRI, e.g.: @code
struct N_empty {
   static const unsigned index = 0;
   static std::string const & iri() {
      static const std::string str="";
      return str;
   }
   static std::string const & prefix() {
      static const std::string str="";
      return str;
   }
   typedef ::owlcpp::Ns_id id_type;
   static id_type id() {return id_type(index);}
}; @endcode

*******************************************************************************/
OWLCPP_GENERATE_IRI_TAGS(OWLCPP_IRI_LIST_SYSTEM, 0)

}//namespace terms
}//namespace owlcpp
#endif /* IRI_TAGS_SYSTEM_HPP_ */
