/** @file "/owlcpp/include/owlcpp/terms/uri_tags.hpp"
part of owlcpp project.
@n Distributed under the Boost Software License, Version 1.0; see doc/license.txt.
@n Copyright Mikhail K Levin 2010
*******************************************************************************/
#ifndef URI_TAGS_HPP_
#define URI_TAGS_HPP_
#include <string>
#include "owlcpp/terms/uri_macro.hpp"
#include "owlcpp/ns_id.hpp"

namespace owlcpp{ namespace terms{

/**@struct N_xxx
@brief Namespace tag classes generated by macro OWLCPP_GENERATE_NAMESPACE_TYPES
@details Declare types for each standard IRI, e.g.: @code
struct N_rdfs {
   static const unsigned index = 3;
   static std::string const & iri() {
      static const std::string str="http://www.w3.org/2000/01/rdf-schema";
      return str;
   }
   static std::string const & prefix() {
      static const std::string str="rdfs";
      return str;
   }
   typedef ::owlcpp::Ns_id id_type;
   static id_type id() {return id_type(index);}
}; @endcode
*******************************************************************************/
OWLCPP_GENERATE_STD_NAMESPACE_TYPES


}//namespace terms
}//namespace owlcpp

#endif /* URI_TAGS_HPP_ */
