#!/bin/sh
# owl_cpp/doc/generate_revision
# part of owl_cpp project.
# Distributed under the Boost Software License, Version 1.0; see doc/license.txt.
# Copyright Mikhail K Levin 2011
#
# This script will generate header file defining current code revision.
# Uses "git describe" command.
# Run manually or invoke from post-commit and post-checkout git hook scripts.

f="out/include/revision.hpp"
v=$(git describe --always --dirty=*)
echo >$f "#define CODE_REVISION \"$v\""
