/** @file "/owl_cpp/include/owl_cpp/terms/term_tags.hpp"
part of owl_cpp project.
Distributed under GNU Lesser General Public License; see doc/license.txt.
@date 2010 @author Mikhail K Levin
*******************************************************************************/
#ifndef TERM_TAGS_HPP_
#define TERM_TAGS_HPP_
#include <string>
#include "term_macro.hpp"
#include "term_methods.hpp"
#include "uri_tags.hpp"
#include "owl_cpp/ns_id.hpp"
#include "owl_cpp/node_id.hpp"

namespace owl_cpp{ namespace terms{

/** @struct T_xxx_XXX
@brief Common term classes generated by macro OWLCPP_GENERATE_TERM_TYPES
@details Declare types for each standard triplet type;
The type of a triplet is determined by the type of its predicate
e.g.: @code
struct T_rdfs_subClassOf {
   typedef Ns_rdfs ns_type;
   typedef Node_id id_type;
   static const unsigned index = 1;
   static const std::string name;
}; @endcode
*******************************************************************************/
OWLCPP_GENERATE_STD_TERM_TYPES

}//namespace terms

}//namespace owl_cpp
#endif /* TERM_TAGS_HPP_ */
